services:
  fdroidserver:
    image: docker.io/austozi/fdroidserver:latest
    container_name: fdroidserver
    restart: unless-stopped
    user: "1000:1000"
    environment:
      TZ: Europe/London      
      FDROID_REPO_URL: https://localhost/repo # change me
      FDROID_REPO_NAME: F-Droid Repository
      FDROID_REPO_ICON: fdroid.png
      FDROID_REPO_DESCRIPTION: A personal app repository for Android devices.
      FDROID_UPDATE_INTERVAL: 12h
    volumes:
      - ./config/fdroid:/fdroid
      - ./config/update-scripts:/update-scripts:ro
  nginx:
    image: ghcr.io/linuxserver/nginx:latest
    container_name: fdroid
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
    volumes:
      - ./config:/config
      - ./config/fdroid/repo:/config/www/repo:ro
    expose:
      - 80
    depends_on:
      - fdroidserver
    networks:
      - frontend
networks:
  frontend:
